### ISSUE TITLE
Error 403 with "destroy" requests

### ISSUE THREAD

**Issue by hmirza0077** [amirasaran/django-restful-admin#12]
Hi
I think there's a bug with DELETE requests.
In your "get_permission_map" method, you have a dictionary that contains all the request methods.
The key of this dictionary with deletion operations is "delete".
And in your "_has_perm_action" method, you're checking that whether "action" is in your dictionary(perm_map) or not but in deletion operations "action" will be equal to "destroy" and that means for all DELETE requests, we have an 403 Error.

**Comment by the-einstein** [comment]
Is there anyone who could overcome this issue?

**Comment by amirasaran** [comment]
@the-einstein @hmirza0077 
can you create a pull request for this issue?
