### ISSUE TITLE
Restrict access to admin endpoints

### ISSUE THREAD

**Issue by MiltosD** [amirasaran/django-restful-admin#2]
How can we restrict access to the provided endpoints for either GET and POST? It seems that the endpoints are accessible from anyone, even without logging in.

**Comment by amirasaran** [comment]
@MiltosD I'm sorry for having responded late.
you can define a custom view. your custom view has all [ModelViewSet](https://www.django-rest-framework.org/api-guide/viewsets/#modelviewset) features.

```
from django_restful_admin import RestFulModelAdmin, site
from .models improt YourModel

class YourModelAdminView(RestFulModelAdmin):
     permission_classes = [IsAutenticatedUser]

site.register(YourModel, YourModelAdminView)
```
