### ISSUE TITLE
If multiple models are sen't to register, it only stores the last one

### ISSUE THREAD

**Issue by gsilvapt** [amirasaran/django-restful-admin#3]
In the [register](https://github.com/amirasaran/django-restful-admin/blob/master/django_restful_admin/models.py#L70) function, when an array of models is sent, only the last one is  is stored. 

The code explicitly calls the parameter `model_or_iterable`. I was unable to decipher what is not working as expected but I am keen on it being related with the `options` variable. Perhaps it needs a deep copying to another variable instead of itself.

**Comment by amirasaran** [comment]
Hi,
Dear @gsilvapt 

you can use like this 
`site.register([Model1,Model2], YourApiModelAdmin)`
OR
`site.register([Model1,Model2])`


in the next version, I will add a decorator and then you can decorate your ModelAdmin and register with args like this:

```
@api_admin.register(VerificationText)
class BaseRestFulModelAdmin(api_admin.RestFulModelAdmin):
    authentication_classes = (CustomTokenAuthentication,)
```
