### ISSUE TITLE
When I add to apps it throws exception, when removed it doesnt throw

### ISSUE THREAD

**Issue by amerepos** [amirasaran/django-restful-admin#4]
raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by amirasaran** [comment]
I will check it.

**Comment by amirasaran** [comment]
@appple Can you share any more data?

**Comment by amirasaran** [comment]
@appple try the new version
